# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE
# Create your own local_prod.py and import this module there to
# override variables and add new ones.

from .base import *

import os
import dj_database_url


DEBUG = False

BASE_DIR_ABS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if 'ADMIN_EMAIL' in os.environ:
    ADMINS = (('Admin', os.environ['ADMIN_EMAIL']), )

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "")

# Parse database configuration from $DATABASE_URL
DATABASES = {
    'default': dj_database_url.config()
}
DATABASES['default']['CONN_MAX_AGE'] = 500

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', "*").split(',')]

# Email backend
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', "")
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))

# Email credentials
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', "")
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', "")
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', "")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR_ABS, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
#STATICFILES_DIRS = (
#    os.path.join(BASE_DIR_ABS, 'static'),
#)

MEDIA_ROOT = os.path.join(BASE_DIR_ABS, 'media')

# These are all the languages Spirit provides.
# https://www.transifex.com/projects/p/spirit/
gettext_noop = lambda s: s
LANGUAGES = [
    ('de', gettext_noop('German')),
    ('en', gettext_noop('English')),
    ('es', gettext_noop('Spanish')),
    ('fr', gettext_noop('French')),
    ('pl', gettext_noop('Polish')),
    ('pl-pl', gettext_noop('Poland Polish')),
    ('ru', gettext_noop('Russian')),
    ('sv', gettext_noop('Swedish')),
    ('zh-hans', gettext_noop('Simplified Chinese')),
]

# Default language
LANGUAGE_CODE = os.environ.get('DEFAULT_LANGUAGE_CODE', 'en')

# Keep templates in memory
del TEMPLATES[0]['APP_DIRS']
TEMPLATES[0]['OPTIONS']['loaders'] = [
    ('django.template.loaders.cached.Loader', (
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
    )),
]

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
MIDDLEWARE_CLASSES.extend([
    'whitenoise.middleware.WhiteNoiseMiddleware',
])

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
